---

- name: "add mariadb repository"
  template:
    src: "repository-redhat.j2"
    dest: /etc/yum.repos.d/mariadb.repo
    owner: root
    group: root
    mode: 0644
  when: mariadb_repo_state

- name: "remove mariadb repository"
  file:
    path: /etc/yum.repos.d/mariadb.repo
    state: absent
  when: not mariadb_repo_state
